title = "Dumitru Vulpe"
baseURL = "https://www.dumitruvulpe.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally

[params]
  author = "Dumitru Vulpe"
  description = ""
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = ""
    url = "https://github.com/jamestiberiuskirk"

[permalinks]
  "/" = "/:contentbasename"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Platform Engineer CV"
    url = "/platform-engineer"
    weight = 2
  [[menu.main]]
    name = "Download PDFs"
    url = "#pdfs"
    weight = 3
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/JamesTiberiusKirk"
    weight = 4
[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
